const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Shape3D,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Follow,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPosToObject
	];
};
self.C3_JsPropNameTable = [
	{дорога: 0},
	{СледитьЗа: 0},
	{ОграничитьСценой: 0},
	{Машина: 0},
	{автомобиль: 0},
	{Твердый: 0},
	{Пуля: 0},
	{Поворот: 0},
	{машинка1: 0},
	{машинка2: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{"3DФигуры": 0},
	{Твёрдый: 0},
	{"3DФигуры2": 0},
	{"3D": 0},
	{"3DФигуры4": 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Синусоида: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{коробки: 0},
	{Орбита: 0},
	{"3DФигуры5": 0},
	{Спрайт8: 0},
	{Якорь: 0},
	{СледоватьЗа: 0},
	{Текст: 0},
	{макдоналс: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{ВводТекста: 0},
	{счет: 0}
];

self.InstanceType = {
	дорога: class extends self.ISpriteInstance {},
	автомобиль: class extends self.ISpriteInstance {},
	машинка1: class extends self.ISpriteInstance {},
	машинка2: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	_3DФигуры: class extends self.I3DShapeInstance {},
	_3DФигуры2: class extends self.I3DShapeInstance {},
	_3D: class extends self.I3DShapeInstance {},
	_3DФигуры4: class extends self.I3DShapeInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	_3DФигуры5: class extends self.I3DShapeInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	макдоналс: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {}
}