const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Shape3D,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Shape3D.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{дорога: 0},
	{СледитьЗа: 0},
	{ОграничитьСценой: 0},
	{Машина: 0},
	{автомобиль: 0},
	{Твердый: 0},
	{Пуля: 0},
	{Поворот: 0},
	{машинка1: 0},
	{машинка2: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{дом: 0},
	{Твёрдый: 0},
	{домС: 0},
	{домЖ: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{"3DФигуры": 0},
	{Синусоида: 0},
	{Спрайт5: 0},
	{"3DФигуры2": 0},
	{сщёт: 0},
	{Якорь: 0},
	{Текст: 0}
];

self.InstanceType = {
	дорога: class extends self.ISpriteInstance {},
	автомобиль: class extends self.ISpriteInstance {},
	машинка1: class extends self.ISpriteInstance {},
	машинка2: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	дом: class extends self.ISpriteInstance {},
	домС: class extends self.I3DShapeInstance {},
	домЖ: class extends self.I3DShapeInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	_3DФигуры: class extends self.I3DShapeInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	_3DФигуры2: class extends self.I3DShapeInstance {},
	Текст: class extends self.ITextInstance {}
}