const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Car,
		C3.Behaviors.Sin,
		C3.Plugins.Shape3D,
		C3.Behaviors.Follow,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{вертикально: 0},
	{правоВерх: 0},
	{горизонтально: 0},
	{горизонтально2: 0},
	{машинки: 0},
	{Твёрдый: 0},
	{машинки2: 0},
	{машинки3: 0},
	{Поворот: 0},
	{Пуля: 0},
	{машинки4: 0},
	{машинки5: 0},
	{машинки6: 0},
	{машинки7: 0},
	{машинки8: 0},
	{автомобильигрока: 0},
	{машинки9: 0},
	{машинки10: 0},
	{Спрайт: 0},
	{СледитьЗа: 0},
	{ОграничитьСценой: 0},
	{Машина: 0},
	{мояМашина: 0},
	{Спрайт2: 0},
	{машинки12: 0},
	{дом1крыша: 0},
	{дом: 0},
	{дом2: 0},
	{дом3: 0},
	{зебра: 0},
	{Синусоида: 0},
	{человекидет: 0},
	{дом4: 0},
	{дом3крыша: 0},
	{Спрайт3: 0},
	{коробк: 0},
	{зебра2: 0},
	{дом5: 0},
	{дом6: 0},
	{дом7: 0},
	{дом8: 0},
	{Спрайт4: 0},
	{коробк2: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{"3DФигуры": 0},
	{"3DФигуры2": 0},
	{"3DФигуры3": 0},
	{СледоватьЗа: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{пулемет: 0},
	{коробоки: 0}
];

self.InstanceType = {
	вертикально: class extends self.ISpriteInstance {},
	правоВерх: class extends self.ISpriteInstance {},
	горизонтально: class extends self.ISpriteInstance {},
	горизонтально2: class extends self.ISpriteInstance {},
	машинки: class extends self.ISpriteInstance {},
	машинки2: class extends self.ISpriteInstance {},
	машинки3: class extends self.ISpriteInstance {},
	машинки4: class extends self.ISpriteInstance {},
	машинки5: class extends self.ISpriteInstance {},
	машинки6: class extends self.ISpriteInstance {},
	машинки7: class extends self.ISpriteInstance {},
	машинки8: class extends self.ISpriteInstance {},
	автомобильигрока: class extends self.ISpriteInstance {},
	машинки9: class extends self.ISpriteInstance {},
	машинки10: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	мояМашина: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	машинки12: class extends self.ISpriteInstance {},
	дом1крыша: class extends self.ISpriteInstance {},
	дом: class extends self.ISpriteInstance {},
	дом2: class extends self.ISpriteInstance {},
	дом3: class extends self.ISpriteInstance {},
	зебра: class extends self.ISpriteInstance {},
	человекидет: class extends self.ISpriteInstance {},
	дом4: class extends self.ISpriteInstance {},
	дом3крыша: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	коробк: class extends self.ISpriteInstance {},
	зебра2: class extends self.ISpriteInstance {},
	дом5: class extends self.ISpriteInstance {},
	дом6: class extends self.ISpriteInstance {},
	дом7: class extends self.ISpriteInstance {},
	дом8: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	коробк2: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	_3DФигуры: class extends self.I3DShapeInstance {},
	_3DФигуры2: class extends self.I3DShapeInstance {},
	_3DФигуры3: class extends self.I3DShapeInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	пулемет: class extends self.ISpriteInstance {}
}